version: "3"

services:
    api:
        container_name: back
        build: ./code-10
        command: yarn run start
        ports:
            - "3333:3333"
        environment:
            - DATABASE_URL=mongodb://mongo/code00
            - PORT=3333
    mongo:
        container_name: db_code
        image: mongo:latest
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
    front:
        container_name: front
        build: ./code-00       
        command: yarn run start 
        ports:
            - '3000:3000'
volumes:
  mongodata: